"""
核心数据类型定义 — CanonicalMessage 及其相关类型
Core data type definitions — CanonicalMessage and related types.

Layer 0: No internal imports allowed (except shared/enums.py).

CanonicalMessage 演进规则（Evolution Rules）:
  ✅ 允许: 新增字段（必须有默认值）
           Add new fields (must have default values)
  ❌ 禁止: 删除字段、重命名字段、修改已有字段类型
           Remove fields, rename fields, or change existing field types
  新增 ContentPart 子类型时，已有 Transformer 收到未知 part 类型时应跳过而非报错。
  When adding new ContentPart subtypes, existing Transformers must skip unknown
  part types rather than raising errors.

schema_version occupies slot for future migration tooling.
schema_version 为未来迁移工具占位。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from orchestration.shared.enums import Capability, ContentPartType, ProviderID, Role, TaskStatus


# ---------------------------------------------------------------------------
# Content Parts / 内容块
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class TextPart:
    """
    纯文本内容块 / Plain text content part.
    Most common content type. 最常见的内容类型。
    """

    text: str
    type: ContentPartType = ContentPartType.TEXT


@dataclass(frozen=True)
class ImagePart:
    """
    图像内容块 / Image content part.
    Supports both URL references and base64-encoded data.
    支持 URL 引用和 base64 编码数据。
    """

    url: str = ""                  # 图像 URL / Image URL
    data: str = ""                 # base64 编码数据 / Base64-encoded data
    media_type: str = "image/jpeg" # MIME 类型 / MIME type
    type: ContentPartType = ContentPartType.IMAGE


@dataclass(frozen=True)
class ToolCallPart:
    """
    工具调用请求块 / Tool call request part.
    Generated by the assistant when it wants to invoke a tool.
    由 assistant 生成，表示希望调用某个工具。
    """

    tool_call_id: str              # 唯一调用 ID，用于匹配结果 / Unique call ID to match result
    tool_name: str                 # 工具名称 / Tool name
    arguments: dict[str, Any]      # 工具参数（JSON 可序列化）/ Tool arguments (JSON-serializable)
    type: ContentPartType = ContentPartType.TOOL_CALL


@dataclass(frozen=True)
class ToolResultPart:
    """
    工具调用结果块 / Tool call result part.
    Returned by the tool executor to the conversation context.
    由工具执行器返回到对话上下文。
    """

    tool_call_id: str              # 对应的调用 ID / Corresponding call ID
    content: str                   # 结果内容（字符串化）/ Result content (stringified)
    is_error: bool = False         # 是否执行失败 / Whether execution failed
    type: ContentPartType = ContentPartType.TOOL_RESULT


# Union type for all content parts / 所有内容块的联合类型
ContentPart = TextPart | ImagePart | ToolCallPart | ToolResultPart


# ---------------------------------------------------------------------------
# Tool definition / 工具定义
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CanonicalTool:
    """
    工具定义（传给 LLM 的工具描述）
    Tool definition passed to LLM for function calling.
    """

    name: str
    description: str
    input_schema: dict[str, Any]    # JSON Schema 格式 / JSON Schema format
    tool_id: str = ""               # 内部 ID，可选 / Internal ID, optional


# ---------------------------------------------------------------------------
# Core message type / 核心消息类型
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CanonicalMessage:
    """
    系统统一消息格式 — 跨所有 provider 的标准消息表示
    System-unified message format — canonical representation across all providers.

    This is the lingua franca of the orchestration system. Every provider
    transformer converts FROM this format to their own API format, and
    converts responses BACK to CanonicalMessage / ProviderResult.
    这是编排系统的通用语。每个 provider transformer 将此格式转换为各自的
    API 格式，并将响应转换回 CanonicalMessage / ProviderResult。

    Immutable (frozen=True): prevents accidental mutation in pipeline.
    不可变（frozen=True）：防止管道中意外修改。
    """

    role: Role                           # system | user | assistant | tool
    content: list[ContentPart]           # One or more content parts / 一个或多个内容块
    message_id: str = ""                 # 可选消息 ID / Optional message ID
    schema_version: int = 1              # 演进占位，迁移工具使用 / Evolution placeholder for migration tooling
    metadata: dict[str, Any] = field(default_factory=dict)  # 扩展元数据 / Extension metadata

    def char_count(self) -> int:
        """
        计算消息的字符数（provider 无关）
        Calculate character count for this message (provider-agnostic).

        Used for context truncation decisions. Stored in DB as `char_count`
        on the session, never as token count to remain provider-independent.
        用于上下文截断决策。在 DB 中存储为 session 的 `char_count`，
        而非 token 数，以保持 provider 无关性。
        """
        total = 0
        for part in self.content:
            if isinstance(part, TextPart):
                total += len(part.text)
            elif isinstance(part, ToolCallPart):
                total += len(part.tool_name) + len(str(part.arguments))
            elif isinstance(part, ToolResultPart):
                total += len(part.content)
        return total


# ---------------------------------------------------------------------------
# Run context / 运行上下文
# ---------------------------------------------------------------------------


@dataclass
class RunContext:
    """
    请求级运行上下文 — 跨所有组件透传
    Request-scoped run context — propagated across all components.

    trace_id is pre-allocated from Sprint 1 so it flows through all layers
    from the start; full OTel integration added in Sprint 8.
    trace_id 从 Sprint 1 起预分配，从一开始就流经所有层；
    完整 OTel 集成在 Sprint 8 中添加。
    """

    tenant_id: str
    session_id: str
    task_id: str
    trace_id: str = ""     # Sprint 3 起透传，Sprint 8 接 OTel / Propagated from Sprint 3, OTel in Sprint 8
    user_id: str = ""


# ---------------------------------------------------------------------------
# Task planning types / 任务规划类型
# ---------------------------------------------------------------------------


@dataclass
class SubTask:
    """
    由主 LLM 分解出的子任务 / Sub-task decomposed by the coordinator LLM.

    Each subtask is assigned to exactly one provider by the CapabilityRouter.
    每个子任务由 CapabilityRouter 分配给恰好一个 provider。

    context_slice: minimal context the sub-agent needs, explicitly allocated
    by the coordinator. Sub-agents have NO access to full session history.
    context_slice：子 Agent 需要的最小上下文，由协调者明确分配。
    子 Agent 没有访问完整会话历史的权限。
    """

    subtask_id: str
    description: str                              # 人类可读描述 / Human-readable description
    capability: Capability                        # 所需能力 / Required capability
    context_slice: list[CanonicalMessage]         # 分配给子 Agent 的上下文 / Context allocated to sub-agent
    provider_id: ProviderID = ProviderID.ANTHROPIC # CapabilityRouter 填充 / Filled by CapabilityRouter
    transformer_version: str = "v1"              # CapabilityRouter 填充 / Filled by CapabilityRouter
    depends_on: list[str] = field(default_factory=list)  # 依赖的子任务 ID / Dependency subtask IDs
    skill_id: str = ""                            # 若为 Skill 类型，填写 skill_id / Skill ID if SKILL type
    tools: list[Any] = field(default_factory=list)  # CanonicalTool list for function calling ★ Sprint 11
    status: TaskStatus = TaskStatus.PENDING
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class TaskPlan:
    """
    主 LLM 生成的完整任务计划 / Complete task plan generated by coordinator LLM.
    Contains ordered subtasks that ParallelExecutor will schedule.
    包含 ParallelExecutor 将调度的有序子任务。
    """

    plan_id: str
    subtasks: list[SubTask]
    summary: str = ""                             # 计划摘要 / Plan summary
    metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Provider result / Provider 结果
# ---------------------------------------------------------------------------


@dataclass
class StreamChunk:
    """
    流式响应块 / Streaming response chunk from a provider adapter.
    """

    delta: str                     # 增量文本内容 / Incremental text content
    is_final: bool = False         # 是否为最后一块 / Whether this is the final chunk
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ProviderResult:
    """
    Provider 调用结果 — 标准化的 provider 响应
    Provider call result — standardized provider response.

    char_count is computed from content (not stored separately in this object),
    used by ResultAggregator for overflow detection.
    char_count 从 content 计算（不单独存储），由 ResultAggregator 用于溢出检测。
    """

    subtask_id: str
    provider_id: ProviderID
    content: str                           # 主文本结果 / Primary text result
    transformer_version: str = "v1"
    tokens_used: int = 0                   # 实际 token 用量（来自 provider 响应头）/ Actual tokens from response
    latency_ms: float = 0.0
    raw_response: dict[str, Any] = field(default_factory=dict)  # 原始响应（调试用）/ Raw response for debugging
    tool_calls: list[Any] = field(default_factory=list)  # ToolCallPart list if LLM requested tools ★ Sprint 11
    metadata: dict[str, Any] = field(default_factory=dict)

    def char_count(self) -> int:
        """内容字符数 / Character count of content."""
        return len(self.content)
