"""
PostgreSQL ORM 模型定义（SQLAlchemy 2.0 异步风格）
PostgreSQL ORM model definitions (SQLAlchemy 2.0 async style).

Layer 4: Only imports from shared/.

Tables / 表:
  tenants  — 租户主表
  sessions — 对话会话（含 RLS 隔离，messages JSONB）
  tasks    — 任务记录（含 RLS 隔离，result JSONB）

RLS 策略需在首次建表后通过 bootstrap.py 执行，参见 engine.py 中的 rls_ddl。
RLS policies must be applied after table creation via bootstrap.py, see engine.py rls_ddl.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import ARRAY, DateTime, Float, Index, Integer, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ---------------------------------------------------------------------------
# pgvector support — optional dependency for ANN-capable embedding column
# pgvector 支持 — 可选依赖，用于支持 ANN 索引的向量列
# ---------------------------------------------------------------------------

# Default embedding dimension (OpenAI text-embedding-3-small / ada-002 compatible)
# 默认向量维度（兼容 OpenAI text-embedding-3-small / ada-002）
EMBEDDING_DIM: int = 1536

try:
    from pgvector.sqlalchemy import Vector as _Vector  # type: ignore[import-untyped]
    _EMBEDDING_COLUMN_TYPE: object = _Vector(EMBEDDING_DIM)
    PGVECTOR_AVAILABLE: bool = True
except ImportError:
    _EMBEDDING_COLUMN_TYPE = ARRAY(Float)
    PGVECTOR_AVAILABLE = False


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    """所有模型的基类 / Base class for all models."""
    pass


# ---------------------------------------------------------------------------
# Tenants / 租户表
# ---------------------------------------------------------------------------

class TenantRow(Base):
    """
    租户主表 — 无 RLS（平台级数据）
    Tenant master table — no RLS (platform-level data).
    """

    __tablename__ = "tenants"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    settings: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )


# ---------------------------------------------------------------------------
# Sessions / 会话表
# ---------------------------------------------------------------------------

class SessionRow(Base):
    """
    对话会话表 — 启用 RLS，按 tenant_id 隔离
    Conversation session table — RLS enabled, isolated by tenant_id.

    messages: JSONB 列存储完整对话历史（序列化的 CanonicalMessage 列表）
              JSONB column stores full conversation history (serialized CanonicalMessage list)
    char_count: provider 无关的字符数，驱动截断策略
                Provider-agnostic char count, drives truncation strategy
    """

    __tablename__ = "sessions"

    session_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    messages: Mapped[list] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    char_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        Index("ix_sessions_tenant_updated", "tenant_id", "updated_at"),
    )


# ---------------------------------------------------------------------------
# Tasks / 任务表
# ---------------------------------------------------------------------------

class TaskRow(Base):
    """
    任务记录表 — 启用 RLS，按 tenant_id 隔离
    Task record table — RLS enabled, isolated by tenant_id.

    input_data: 原始任务请求 / Original task request
    task_plan:  分解后的 TaskPlan（主 LLM 生成）/ Decomposed TaskPlan (generated by coordinator)
    result:     最终汇总结果 / Final aggregated result
    """

    __tablename__ = "tasks"

    task_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True), nullable=True, index=True
    )
    status: Mapped[str] = mapped_column(
        String(50), nullable=False, default="pending"
    )
    input_data: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    task_plan: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    result: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        Index("ix_tasks_tenant_status", "tenant_id", "status"),
        Index("ix_tasks_tenant_session", "tenant_id", "session_id"),
    )


# ---------------------------------------------------------------------------
# Usage Records / 用量计费记录表
# ---------------------------------------------------------------------------


class UsageRow(Base):
    """
    用量计费记录表 — 启用 RLS，按 tenant_id 隔离
    Usage billing record table — RLS enabled, isolated by tenant_id.

    Records token usage per provider per task for billing aggregation.
    记录每个任务、每个 provider 的 token 用量，用于计费聚合。

    cost_usd: 预留字段，用于后续按 provider 单价计算费用
              Reserved field for calculating cost at provider unit price
    """

    __tablename__ = "usage_records"

    record_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    task_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True), nullable=True, index=True
    )
    provider_id: Mapped[str] = mapped_column(String(50), nullable=False)
    tokens_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    __table_args__ = (
        Index("ix_usage_records_tenant_created", "tenant_id", "created_at"),
        Index("ix_usage_records_tenant_provider", "tenant_id", "provider_id"),
    )


# ---------------------------------------------------------------------------
# Document Embeddings / 文档向量嵌入表
# ---------------------------------------------------------------------------


class DocumentEmbeddingRow(Base):
    """
    文档向量嵌入表 — 启用 RLS，按 tenant_id 隔离
    Document embedding table — RLS enabled, isolated by tenant_id. ★ Sprint 13

    embedding: ARRAY(Float) 存储浮点向量；生产环境建议迁移为 pgvector VECTOR 类型以支持 ANN 索引。
               ARRAY(Float) stores float vector; in production consider migrating to pgvector VECTOR
               type to enable ANN index (IVFFlat / HNSW).
    doc_id: 调用方提供的文档标识符，同一租户内唯一
            Caller-provided document identifier, unique within a tenant.
    """

    __tablename__ = "document_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    doc_id: Mapped[str] = mapped_column(String(256), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list] = mapped_column(_EMBEDDING_COLUMN_TYPE, nullable=False)  # type: ignore[arg-type]
    doc_metadata: Mapped[dict] = mapped_column(
        "metadata", JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    __table_args__ = (
        UniqueConstraint("tenant_id", "doc_id", name="uq_document_embeddings_tenant_doc"),
        Index("ix_document_embeddings_tenant", "tenant_id"),
    )


# ---------------------------------------------------------------------------
# Tenant API Keys / 租户 API 密钥表
# ---------------------------------------------------------------------------


class TenantKeyRow(Base):
    """
    租户 API 密钥表 — 每个租户可为每个 provider 存储自定义 API Key，覆盖全局配置。
    Tenant API key table — each tenant can store per-provider API keys to override global config.
    ★ Sprint 15

    security note / 安全说明:
      api_key 以明文存储（生产环境建议接入 KMS 加密）。
      api_key stored as plaintext (production should encrypt via KMS).
    """

    __tablename__ = "tenant_api_keys"

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    provider_id: Mapped[str] = mapped_column(String(64), nullable=False)
    api_key: Mapped[str] = mapped_column(String(1024), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        UniqueConstraint("tenant_id", "provider_id", name="uq_tenant_api_keys"),
    )


# ---------------------------------------------------------------------------
# Templates / 路由模板表
# ---------------------------------------------------------------------------


class TemplateRow(Base):
    """
    路由模板表 — 启用 RLS，按 tenant_id 隔离
    Routing template table — RLS enabled, isolated by tenant_id.

    capabilities: JSONB，存储各能力对应的 provider_id（如 {"text": "anthropic", "image": null}）
                  JSONB storing per-capability provider_id mappings.
    """

    __tablename__ = "templates"

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    capabilities: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    __table_args__ = (
        UniqueConstraint("tenant_id", "name", name="uq_templates_tenant_name"),
        Index("ix_templates_tenant_created", "tenant_id", "created_at"),
    )


# ---------------------------------------------------------------------------
# RLS DDL（在 bootstrap.py 中执行）/ RLS DDL (executed in bootstrap.py)
# ---------------------------------------------------------------------------

# 以字符串形式提供，由 bootstrap.py 执行；不作为 SQLAlchemy event 以保持控制权。
# Provided as strings, executed by bootstrap.py; not as SA events to keep explicit control.
RLS_SETUP_SQL = [
    # sessions 表 / sessions table
    "ALTER TABLE sessions ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE sessions FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON sessions",
    "CREATE POLICY deny_by_default ON sessions USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON sessions",
    (
        "CREATE POLICY tenant_isolation ON sessions "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
    # tasks 表 / tasks table
    "ALTER TABLE tasks ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE tasks FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON tasks",
    "CREATE POLICY deny_by_default ON tasks USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON tasks",
    (
        "CREATE POLICY tenant_isolation ON tasks "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
    # usage_records 表 / usage_records table
    "ALTER TABLE usage_records ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE usage_records FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON usage_records",
    "CREATE POLICY deny_by_default ON usage_records USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON usage_records",
    (
        "CREATE POLICY tenant_isolation ON usage_records "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
    # document_embeddings 表 / document_embeddings table ★ Sprint 13
    "ALTER TABLE document_embeddings ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE document_embeddings FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON document_embeddings",
    "CREATE POLICY deny_by_default ON document_embeddings USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON document_embeddings",
    (
        "CREATE POLICY tenant_isolation ON document_embeddings "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
    # tenant_api_keys 表 / tenant_api_keys table ★ Sprint 15
    "ALTER TABLE tenant_api_keys ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE tenant_api_keys FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON tenant_api_keys",
    "CREATE POLICY deny_by_default ON tenant_api_keys USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON tenant_api_keys",
    (
        "CREATE POLICY tenant_isolation ON tenant_api_keys "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
    # templates 表 / templates table
    "ALTER TABLE templates ENABLE ROW LEVEL SECURITY",
    "ALTER TABLE templates FORCE ROW LEVEL SECURITY",
    "DROP POLICY IF EXISTS deny_by_default ON templates",
    "CREATE POLICY deny_by_default ON templates USING (false)",
    "DROP POLICY IF EXISTS tenant_isolation ON templates",
    (
        "CREATE POLICY tenant_isolation ON templates "
        "USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)"
    ),
]
